### ISSUE TITLE
[Bug] Dataloss silently during streamload 

### ISSUE THREAD

**Issue by link3280** [apache/doris-flink-connector#101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0

### What's Wrong?

We have a job that loads MySQL CDC data into Doris with Doris Flink connector 1.1.0. The Flink logs and metrics show that there are 1464 records written, but Streamload only gets 1463 (verified via Doris select and streamload logs), leaving 1 record missing. 

![image](https://user-images.githubusercontent.com/13482005/218062229-7395e485-72f6-4a73-9c56-0ca36732e152.png)

![image](https://user-images.githubusercontent.com/13482005/218062498-fd966d01-2472-488b-b5e1-4703b905df2a.png)

I'm pretty sure there are no other streamloads getting the remaining 1 record.

### What You Expected?

No data loss.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarvenDuan** [comment]
Did you use watermark in your application?  In Flink, watermarks are implemented as special records holding a timestamp as a Long value. May be a watermark was counted.

**Comment by link3280** [comment]
@DarvenDuan Thanks for your reply! I've found it should be related to https://github.com/apache/doris/issues/13064. Closing this issue.
