### ISSUE TITLE
[Feature] write data to two doris at the same time

### ISSUE THREAD

**Issue by LCehoennardo** [apache/doris-flink-connector#134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

How to change the code so that this connector can write data to two Doris clusters at the same time (to achieve master-slave cluster data synchronization), can you provide some ideas?

### Use case

to achieve master-slave cluster data synchronization

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Is it possible to split the upstream data and write it to different sinks?

**Comment by LCehoennardo** [comment]
> Is it possible to split the upstream data and write it to different sinks?

Thanks for your reply, I have implemented this feature, see https://github.com/LCehoennardo/flink-dual-doris-connector for more.
