### ISSUE TITLE
[Feature] Add documentation to support developers to read

### ISSUE THREAD

**Issue by didiaode18** [apache/doris-flink-connector#145]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Everyone using doris-flink-connector lacks details in Chinese and English documents, such as cdc synchronization

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Thanks, already add https://doris.apache.org/docs/dev/ecosystem/flink-doris-connector/#use-flinkcdc-to-access-multiple-tables-or-the-entire-database-supports-mysql-oracle-postgresql-sqlserver
