### ISSUE TITLE
[Bug] CDCTools job cannot restart from previous checkpoint/savepoint when multiple tables in sync

### ISSUE THREAD

**Issue by cygnusdark** [apache/doris-flink-connector#149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.4.0

### What's Wrong?

CDCTools job cannot restart from previous checkpoint/savepoint when multiple tables in sync.

### What You Expected?

The job should be able to use previous checkpoint/savepoint to restart.

### How to Reproduce?

To reproduce, sync multiple tables, for example:
--including-tables test|test2|test_clone|test_clone2

The reason is that Flink is a stateful application, and it is recommended by official that each stateful operator should have a unique uid.
I fixed this issue by using table name as the uid of its associated sink operators.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
What is the specific error that cannot be started?
