### ISSUE TITLE
[Bug] unique表新增default current_timestamp的列, 有的行没有填充current_timestamp

### ISSUE THREAD

**Issue by EddyChina** [apache/doris-flink-connector#153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.0-alpha

### What's Wrong?

Doris里有个表, 通过alter table add columnt data_ts datetime default current_timestamp的方式增加了一列, 但是有的数据被填充了值, 有的却没有. 

而且使用全库同步的方式建的表新增了这个字段(mysql源表并没有), 有新的数据sink进来后这一列也没有被填充.

### What You Expected?

应该每一行数据都填充或者添加这列时间点之前的数据不填充.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alenfive** [comment]
这是Doris问题，目前好像stream load 不支持默认值，可选的方案是在load前解析当前时间默认值逻辑，并设为当前值

**Comment by DongLiang-0** [comment]
This problem has been fixed recently, and it will be normal on the upcoming 2.0-beta version, You can upgrade it.

**Comment by EddyChina** [comment]
> This problem has been fixed recently, and it will be normal on the upcoming 2.0-beta version, You can upgrade it. [apache/doris#20624](https://github.com/apache/doris/pull/20624)

Awesome. Do you have a planned date for 2.0-beta?

**Comment by DongLiang-0** [comment]
> > This problem has been fixed recently, and it will be normal on the upcoming 2.0-beta version, You can upgrade it. [apache/doris#20624](https://github.com/apache/doris/pull/20624)
> 
> Awesome. Do you have a planned date for 2.0-beta?

At present, 2.0-beta has entered the version voting stage, and the version will be released after the voting.

**Comment by victoyzz** [comment]
i have same problem.
