### ISSUE TITLE
建议集成Postgres数据库

### ISSUE THREAD

**Issue by MR-liuhaha** [apache/doris-flink-connector#163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

Postgres是广泛使用的关系型数据库 , flinkcdc也已适配Postgres的连接. doris可以增加配套使用.使得生态更完善

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinge-1** [comment]
+1
