### ISSUE TITLE
[Feature] Catalog support to enable control of partitions

### ISSUE THREAD

**Issue by zhqu1148980644** [apache/doris-flink-connector#17]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

- Catalog support

### Use case

- create partition before writing to doris.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Hello @zhqu1148980644 , The latest version already supports Catalog
