### ISSUE TITLE
Support Chinese table name and column names[Feature] 

### ISSUE THREAD

**Issue by chenguoshun** [apache/doris-flink-connector#264]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
The Chinese table name Doris is already supported, you can try it with version 2.x
