### ISSUE TITLE
[Bug]  DorisCatalog queryFenodes

### ISSUE THREAD

**Issue by Bmyymwtao** [apache/doris-flink-connector#280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 2.0.2, doris-flink-connector 1.4.0+

### What's Wrong?

SQLException: Column 'IP' not found

### What You Expected?

![image](https://github.com/apache/doris-flink-connector/assets/74750747/167136f0-c793-4e6e-a891-88ae5313a7ca)
Perhaps related to the doris version, doris 2.x gets a resultset without an ip field when executing SHOW FRONTENDS.
The result of my dbeaver execution should be to use the Host field

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
#281 fix this
