### ISSUE TITLE
[Feature] 是否支持https和单独配置Doris be Nodes

### ISSUE THREAD

**Issue by SamuelBin** [apache/doris-flink-connector#310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

现在在客户现场遇到了以下问题
1、客户的doris集群开启了https，connector无法写入Doris
2、客户现场的doris是夸网断的，一个核心区，一个app区，通过fe的8030返回的be节点是内网ip，客户只提供映射ip，能否对connector单独配置be节点

### Use case

    private String tableIdentifier;
    private String beNodes;
    private boolean enableHttps;
    private boolean ignoreHttpsCA;

    public DorisOptions(String fenodes, String beNodes, String username, String password,
                        String tableIdentifier, boolean enableHttps, boolean ignoreHttpsCA) {
        super(fenodes, username, password);
        this.tableIdentifier = tableIdentifier;
        this.beNodes = beNodes;
        this.enableHttps = enableHttps;
        this.ignoreHttpsCA = ignoreHttpsCA;
    }

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
![image](https://github.com/apache/doris-flink-connector/assets/7951521/73b9e895-9544-46c1-86ae-26802f558da4)
