### ISSUE TITLE
[Feature] 支持写入cdc 更新和删除记录。

### ISSUE THREAD

**Issue by melin** [apache/doris-flink-connector#321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

有一个很常见的场景，在一些政府部门（医保数据上报）。市向省、省向国家层层上报数据，需要保留删除和修改数据，防止下一级删除数据。在目标表有一个标记字段，记录是删除，更新和插入。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
This is already supported
