### ISSUE TITLE
[Bug] The status of open scanner result from Doris BE{host='xxx.xxx.xxx.xxx', port=9060} is 'INVALID_ARGUMENT', error message is: [(xxx.xxx.xxx.xxx)[INVALID_ARGUMENT]Unknown primitive type(26)].

### ISSUE THREAD

**Issue by SamuelBin** [apache/doris-flink-connector#364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.2.1

### What's Wrong?

Doris Source
The status of open scanner result from Doris BE{host='xxx.xxx.xxx.xxx', port=9060} is 'INVALID_ARGUMENT', error message is: [(xxx.xxx.xxx.xxx)[INVALID_ARGUMENT]Unknown primitive type(26)].

### What You Expected?

ok

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Check if there are datev2 datetimev2 decimalv3 and other types. If so, you can upgrade the doris version to 2.0
