### ISSUE TITLE
[Bug] The `DorisTypeMapper` datetime type will lose precision when converted to flink type

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/doris-flink-connector#378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

The field type of my doris table is datetime at the millisecond level, but when I use flink doris catalog, the writing will only be at the second level.

### What You Expected?

The types should correspond

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
![image](https://github.com/apache/doris-flink-connector/assets/40817998/578bfc0c-2882-420b-bd0f-5d39db360823)
The confusing thing is that the precision value is 0. I think there is some problem with whether doris handles metadata. Here is another issue：
https://github.com/apache/doris/issues/34437

**Comment by JNSimba** [comment]
How was that triggered? In theory, the catalog will reach this point
