### ISSUE TITLE
https://github.com/apache/flink-cdc/pull/2315 这是flink cdc 旧版本的BUG file is not a valid field name ,flink cdc 新版版已经修复了

### ISSUE THREAD

**Issue by mdzz9527** [apache/doris-flink-connector#407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

doris-flink-connector是否会跟进修复,

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
The flinkcdc version will be upgraded to 3.1 later.
