### ISSUE TITLE
[Bug] [Source]DorisSplitRecords.finishedSplits()返回的集合有null对象导致的整个flink作业发生NullPointerException

### ISSUE THREAD

**Issue by yingh0ng** [apache/doris-flink-connector#411]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.6.0

### What's Wrong?

DorisSplitRecords.finishSplits()返回的集合里有且仅有一个null对象
1、第一个图里添加分片后是正常的；
2、第二个图的日志显示FetcheTask里的callBack打印出来的finishSplits里仅有一个null对象
![企业微信截图_17194749296203](https://github.com/apache/doris-flink-connector/assets/22335970/5c802109-31d9-4e6e-979b-1eac32b881da)

![企业微信截图_17194741888949](https://github.com/apache/doris-flink-connector/assets/22335970/eabc3457-6d34-459d-a87d-83d05eca47d8)

### What You Expected?

正常执行

### How to Reproduce?

使用doris-flink-connector读取doris的表并写到另一个doris的表里

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Please post the error stack

**Comment by yingh0ng** [comment]
> Please post the error stack

[npe.log](https://github.com/user-attachments/files/16047446/npe.log)

**Comment by yingh0ng** [comment]
@JNSimba Is it possible that there was a reordering of instructions in this place? Because String is immutable, and the previous log has printed split information. And this problem happens occasionally.
![image](https://github.com/apache/doris-flink-connector/assets/22335970/21aa860c-be78-47a0-9390-2ea7ef1eade5)

**Comment by JNSimba** [comment]
@yingh0ng Thank you, could you please post the table schema and DorisSource configuration?

**Comment by JNSimba** [comment]
@yingh0ng Can you try this PR? It fixes the problem that the SplitId of DorisSource is repeated. #414

**Comment by yingh0ng** [comment]
> @yingh0ng Thank you, could you please post the table schema and DorisSource configuration?

Only have table properties of DDL:
```
table:
    properties:
      replication_allocation: 'tag.location.default: 1'
      enable_duplicate_without_keys_by_default: true
```


The DorisSource configuration:
```
connector=doris
fenodes=xxx
table.identifier=database.tableName
username=xxx
password=xxx
doris.request.tablet.size=10(my table`s buckets is 10)
```

**Comment by yingh0ng** [comment]
> @yingh0ng Can you try this PR? It fixes the problem that the SplitId of DorisSource is repeated. #414

Got it. Thank you!
