### ISSUE TITLE
Release Note 1.1.0 

### ISSUE THREAD

**Issue by hf200012** [apache/doris-flink-connector#42]
### Feature

1. Refactoring DorisSouce based on FLIP-27 

3. With the two-phase commit of Stream Load in Doris 1.x version, Flink Doris Connector implements Exactly Once semantics 

4. Support streaming loading in json format, support read_json_by_line instead of strip_outer_array 

### Bugfix

1. fix flink schema and doris schema column mappingn 

2. fix flink date and timestamp type not mapping 

3. Fix row type decimal convert bug 

**Note:**  We will no longer support Flink versions prior to 1.14 in this version, and we will provide long-term support versions for subsequent versions of Flink based on this version.

### Thanks
Thanks to everyone who has contributed to this release:

@aiwenmo 
@bridgeDream 
@cxzl25 
@gj-zhang 
@hf200012 
@JNSimba 
@liuyaolin
@madongz 
@morningman 
@stalary 
@yangzhg 
@Yankee24

**Comment by yuruguo** [comment]
@hf200012 @JNSimba Looking forward to the release of `1.1.0`.
By the way, do we have any plans to implement flink associating doris dimension tables?
