### ISSUE TITLE
[Bug] doris-flink-connector can not import oracle pdb database's data to doris

### ISSUE THREAD

**Issue by Kris1314Love** [apache/doris-flink-connector#424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris 2.0.0
flink 1.17.0
oracle 19c

### What's Wrong?

![image](https://github.com/apache/doris-flink-connector/assets/175302795/23c85c84-6f52-4cd2-ae1f-91d81515ab3b)

### What You Expected?

no error

### How to Reproduce?

In oracle 19c, first step, create a pdb database, second step, create a pdb user,then create a table in the pdb user, finally import the pdb user's table into the doris

### Anything Else?

Looking forward to your reply

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Thanks, this has been resolved by #423
