### ISSUE TITLE
[Bug] doris中如果有表，则不会同步

### ISSUE THREAD

**Issue by liutao-123** [apache/doris-flink-connector#482]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.6

### What's Wrong?

我见代码中是当doris中没有mysql的表才会执行代码：
dorisTables.add(Tuple2.of(targetDb, dorisTable));
因此 doris中如果有表，则不会同步。

### What You Expected?

当doris中有对应的表示希望也能够进行同步，而不是直接过滤。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
It has been fixed and can be tried with 24.0.0

**Comment by vinlee19** [comment]
Maybe you can solve the problem by using  `--single-sink true`
