### ISSUE TITLE
[Bug] Stream load fails when there's no data

### ISSUE THREAD

**Issue by link3280** [apache/doris-flink-connector#53]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0

### What's Wrong?

Stream load fails if there's no data to flush. 

<img width="1155" alt="截屏2022-08-09 17 41 43" src="https://user-images.githubusercontent.com/13482005/183617882-8744e90d-0333-4c30-b808-024f8d081aca.png">

We could fix this by skip the flush if there's no pending data.

### What You Expected?

No failure when there's no input data.

### How to Reproduce?

Submit a job with an empty data source and Doris sink.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
hello, link3280:
1. `all partitions have no load data` is usually an error raised when the data format or partition does not exist.
2. I simulated the scene without data writing locally, and it can be run.

**Comment by link3280** [comment]
@JNSimba Thanks for your explanation.

I was writing to a non-partitioned table, of which DDL is like: 

```
CREATE TABLE `tmp_test` (
  `a` text NULL COMMENT "",
  `update_time` datetime NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`a`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`a`) BUCKETS 32
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"in_memory" = "false",
"storage_format" = "V2"
);
```

BTW, the doris cluster's version 0.15.0 (2pc disabled). Would that be related to the error?

**Comment by link3280** [comment]
I mock a few records in a Kafka topic and submit a Flink job to sink them into a Doris table.

The first checkpoint was good because there're existing data, but the second one fails with `all partitions have no load data`. 

Please see the flink log for details.

![image](https://user-images.githubusercontent.com/13482005/183876623-3f21916f-c1ef-4aaf-884b-b9b335333b28.png)

**Comment by JNSimba** [comment]
Can you provide some sample data sent to the sink operator, let me simulate the test

**Comment by JNSimba** [comment]
hello, link3280, thanks for your reply.
Version 0.15 has this problem. In version 0.15, curl streamload an empty file will also report this error, even if all data is filtered out, this error will also occur. But the 1.X version is normal.

In addition, this change is not suitable: if there is no data entry for a long time, it is easy to cause a particularly long http request.
Version 0.15 can use doris-flink-connector-1.0.3 version first

Thanks~

**Comment by link3280** [comment]
@JNSimba Thanks for your input! Then I'll close the issue and the PR.
