### ISSUE TITLE
[Bug] Multiple doris sink writer error when disable 2pc

### ISSUE THREAD

**Issue by y0908105023** [apache/doris-flink-connector#73]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.1.0

### What's Wrong?

One source stream write to two doris sink on one flink application. All doris sink enable2pc is false, but have one label prefix.
error stack:
![image](https://user-images.githubusercontent.com/8789291/196083718-ccad0a17-ce19-41fd-8371-68425e4b5b6f.png)
 

### What You Expected?

application not error

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
The label of each sink is unique
