### ISSUE TITLE
[Feature] Can one job works for multiples tables?

### ISSUE THREAD

**Issue by 979734140** [apache/doris-flink-connector#96]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

It's wasterful for my system to handle every table with their alone slot, because my tables is not so big and change not so fast.

My temp solution is creating custom streamLoad and doriswriter. And it works for all Listening tables .

### Use case

one job can works for multiples tables

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Yes, your current approach is fine.
In the future, we will support streamload to support the semantics of multiple tables, so that a single sink can support the synchronization of multiple tables.

**Comment by JNSimba** [comment]
The latest version currently supports
